api:
  api_key: YY8sk4w5J2rSowun
  api_secret: 8f*OdlE7YXfB&!LdmHi+Jg*O0:MlTCcN
  base_url: https://api-adapter.dzengi.com
data:
  db_path: data/project.db
default_fetch:
  collect_order_book: false
  end_date: '2025-01-01'
  order_book_depth: 5
  start_date: '2024-01-01'
  symbol: EURUSD
  timeframe: M5
indicators:
  adx:
    period: 14
  candle_patterns:
  - hammer
  - inverted_hammer
  - engulfing
  - doji
  custom_binary:
    threshold: 0.0
  psar:
    max_step: 0.2
    step: 0.02
live_trading:
  combine_signal_logic: AND
  custom_logic: ''
  enabled: false
  manual_override: false
  polling_interval_sec: 60
plugins:
  indicators: []
  indicators_params: {}
  models: []
  models_params: {}
  strategies: []
  strategies_params: {}
risk_management:
  max_daily_trades: 10
  mode: fixed_size
  risk_percent: 2.0
  size_per_trade: 0.1
  stop_loss_pips: 100
  take_profit_pips: 200
  trading_time:
    end_hour: 20
    start_hour: 8
telegram:
  chat_id: ВАШ_CHAT_ID
  send_on_error: true
  send_on_order_close: true
  send_on_order_open: true
  token: ВАШ_TELEGRAM_TOKEN
training:
  batch_size: 64
  ensemble_models: []
  epochs: 50
  model_type: LightGBM
  test_split: 0.2
  use_ensemble: false
